### ISSUE TITLE
ECG Kit - serial data out 

### ISSUE THREAD

**Issue by stanleyoz** [siliconwitchery/s1-ecg-demo#14]
Hi,
We got hold of the S1 ECG Kit from DigiKey, nice .. it blinks LEDs as per heart-beat and pretty stable. Is there a way to code the board so that it can output serially the amplitude of the waveform so we can ingress the data into our gateway via USB etc? It seems the S1 module does not have any data connection out thru the USB-C connector. 
Please advise. 
Thanks.

**Comment by siliconwitch** [comment]
Hello there! Glad to have the board in your hands 🙂

The most simplest option could be to solder a USB to UART dongle to one of the exposed D1/2/3/4 pads on the back of the board. You'd then need to reprogram the nRF and FPGA to pass through UART data to those pins rather than the LED PWM.

Alternatively, you can connect up the onboard USB jack to D1/D2. You'd need to add little wires very carefully to the jack, and then add the relevant USB IP to the FPGA. It's a lot more work, but would give you the most flexibility.

If instead you want to avoid soldering altogether, you could use our [MicroPython](https://docs.siliconwitchery.com/micropython/micropython/) firmware instead. This would let you stream the data to your gateway over Bluetooth (assuming you have the possibility to add that). You'd do this by executing a script that polls the ADC, and then prints the values back to the host. If you wanted to, you could do all kinds of filtering or preprocessing of the samples before sending them over. To send these samples back, you'd simply use the Python `print()` statement. Our MicroPython firmware essentially just turns the S1 into a remote shell that runs over Bluetooth. Check out the [ADC API](https://docs.siliconwitchery.com/micropython/adc/) to see how this would be done.

For all of these options, you'll need to reprogram the ECG kit. You'll need a [TC2030-CTX-NL](https://www.tag-connect.com/product/tc2030-ctx-nl-6-pin-no-legs-cable-with-10-pin-micro-connector-for-cortex-processors) from Tag-Connect, as well as a J-Link programmer. You can also use an nRF52DK board as shown [here](https://docs.siliconwitchery.com/s1-module/s1-module/#programming-the-nrf52).

Hope this helps!

**Comment by stanleyoz** [comment]
Possible solutions ... but can you contact me at stanley"at"amplified.com.au? Due to proprietary nature of this gov medical project, prefer to share more details off the github. Thanks.
